---
- include_tasks:
    file: preflight.yml
    apply:
      become: true
      tags:
        - cbmultimanager_install
        - cbmultimanager_configure
        - cbmultimanager_run

- include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - cbmultimanager_install
  when: __cbmultimanager_do_install | bool

- include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - cbmultimanager_configure
  tags:
    - cbmultimanager_configure
