---
# Output any variables that start with couchbase_*
- name: Show all cbmultimanager variables
  debug:
    var: vars[item]
  with_items: "{{ lookup('varnames', 'cbmultimanager_.+').split(',') }}"
  tags:
    - cbmultimanager_install
    - cbmultimanager_configure
    - cbmultimanager_run

- include: preflight.yml
  become: true
  tags:
    - cbmultimanager_install
    - cbmultimanager_configure
    - cbmultimanager_run

- include: install.yml
  become: true
  when: __cbmultimanager_do_install
  tags:
    - cbmultimanager_install

- include: configure.yml
  become: true
  tags:
    - cbmultimanager_configure
