---
- hosts: cbmultimanager
  become: true
  vars:
    cbmultimanager_configure_firewalld: false
    couchbase_username: Administrator
    couchbase_password: password
  pre_tasks:
    # pre_tasks happen before roles are executed / applied
    # if the cbmultimanager_configure_firewalld is true, make sure the service is installed before proceeding
    - name: Make sure firewalld is installed
      package:
        name: firewalld
        state: present
      when: cbmultimanager_configure_firewalld | default(false)
      tags:
        - cbmultimanager_firewalld
  roles:
    - couchbaselabs.cbmultimanager
  tasks:
    # tasks happen after roles are executed / applied
    # if the cbmultimanager_configure_firewalld is true, make sure the service is started
    - name: Make sure firewalld is started
      service:
        name: firewalld
        state: started
      when: cbmultimanager_configure_firewalld | default(false)
      tags:
        - cbmultimanager_firewalld
    - name: Add port {{ cbmultimanager_bind_port }} (cbmultimanager)
      ansible.posix.firewalld:
        port: "{{ cbmultimanager_bind_port }}/tcp"
        permanent: true
        state: enabled
      when: cbmultimanager_configure_firewalld | default(false)
      tags:
        - cbmultimanager_firewalld
    - name: Make sure firewalld is restarted
      service:
        name: firewalld
        state: restarted
      when: cbmultimanager_configure_firewalld | default(false)
      tags:
        - cbmultimanager_firewalld
